version: "3"

services: 
    database : 
        build: 
            dockerfile: Dockerfile 
            context: ./database
        restart: always
        networks: 
            - moomall
    api :
        depends_on: 
            - database
        build: 
            dockerfile: Dockerfile
            context: ./api 
        restart: always
        networks: 
            - moomall 
        ports:  
            - 5000:3001
        environment: 
            DATABASE_USER : admin
            DATABASE_PASSWORD : 1234
            DATABASE_HOST : database
    website:
        build: 
            dockerfile: Dockerfile 
            context: ./website 
        ports: 
            - 3000:3000
        restart: always
        networks: 
            - moomall
        stdin_open: true
networks: 
    moomall : 